# Generated by Django 3.2 on 2023-05-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='remaining_time',
            field=models.BigIntegerField(blank=True, default=1800, editable=False),
        ),
    ]
