# Generated by Django 3.2 on 2023-05-24 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('backend', '0002_usertoken_remaining_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='remaining_time',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='auth_token',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='backend_usertoken', to='authtoken.token'),
        ),
    ]
