# Generated by Django 3.2 on 2023-05-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20230524_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='auth_token',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='remaining_time',
            field=models.BigIntegerField(blank=True, default=1800, editable=False),
        ),
    ]
